FROM node:18-alpine

WORKDIR /frontend  # Adjusted to reflect the new structure

ENV NEXT_PUBLIC_API_URL=localhost:8000

# Install pnpm
RUN npm install -g pnpm@8

# Copy package files
COPY frontend/package.json frontend/pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy the rest of the application
COPY frontend .

# Expose the port
EXPOSE 3000

# Start the development server (for development, not production)
CMD ["pnpm", "dev"]
